dist: trusty
sudo: false
language: node_js
node_js:
  - '10'
env:
  global:
    - secure: eKieoccdPtAIOYQm7YiAM2+pgEAfkTCONr3vftUAbFGbxTcWsTRVnDoN4QyPFTvjlFiGyl3SV7TXUKfpb3aTSUSjThyiVj8K5/eihbHp4pEgy3IVynMquVawF4jkPBbwjvtfLBiz4kKS2JY4NCiY81th3CyDg+aJsVW4DfklGz+iHH6wKS9DNt+VWhZ0U5XebTnlJ3HcPQ9xLBB1fDyleFuKv4l08ZIRBGcU/aFiWOiQXejkFbjfNBA5kfhs2FAvn0tphevgEVAsK7ojGLOLU9NtSDkY0CHEMV/KAaYU6Aq6pokcwAe5FtX+1UM/HH7l5nimuX+3qylcDim4sgFY1djqN43f23VEc6HT7WaIeUBERZJ2hX1a3zwNhPaMFUdazKpFPKgu1PQArEL03779aSDfeqf+ytOKT7j/fy+bT1vvhONg6srwInYhBC09Txvuf/MrMSYMPR/caiph1Pw3i4RKiVVIhoQQhztoNvWFnnHvGsYTYb1NKq+tEuzRDJhF9lMT1N0Tl2s4vxyFohXhC2pxwvTM3YWFA94gKlTyf+04yCIvdJ0YodVwxmF10fpYkV9e5WaLwbJjtr9LMhOUkDw+tSBxsVBjO6sJe135DsbYimbuFPJUXz2wS2DeOQLEox8WUlZyr/EYyoxVvv87pmxyMSRGLaoIHWqGz45k7yA=
    - secure: VqqZQME/4y0Fw285T3EdFzZFULyrDWenGDZ4g+MfVOaTTtlEHT7wDt0O14SIMMNIGWZTu8aaGyxWcxdcgVguT5HIHYah5TPJq51bVnCAUKjALFymctQz0TQJMoThjm6/k5z9qJ0h6JChyFXJqR3aTVQGv8WXQtwotgegWvn/cm6mi5qG+jdb+PB8tk88/ursHsQh9HUcq7amqEHEGpZQ0JJLbGG8nR0OU/2Svc83hrWiUY2W3GNRZT/9yJepnr0fOTiXTphuzYGwlEG7QukO8IIVytWRAPvIRrE2q8Ik2WMo1etYafKagGPjPcJ43iBMo7fY38FrGH3ZenCOhbzN5xAmCf4Rv1J1312JvFgNbDg9F7o6frq4zs1bxNIIkO9KuzFNANf3b6oAhASB6TP4QmYD0ZSHMoZOCZF0kT4F6lKXokXRcD5LqvVavnmgCDwVsD4FIg3phX1iH7tl/tdqgY+8Pv3jjGiAILyZMhlxO/Q+3pL4nZ9f7aa6OWGa4gbPFOpIWtH+cnNhHkdysE/ebX6PiN/7Gb/HdkbREyJxWoihGYFwWBvEzzOMHTBLoyCY1G3UA5AMh3IQ1MgvaQ1KIJxsZpk6JwIV0xGrGEbIPsFNjyt1WBDxceQNqBl27nM7b/vESVdkI+G940rUHaQ659b0kF/iqBwFPPgczbWcIKs=
    - secure: QNc7vJtgJRJLUUyRfqygWCW/3zvbwgS1NC+0B4iOl/399kEyfwVsD4x6V8jFGrh144OxFIHN1l0/eOICDgpxDJbHXjhWbokCSplySh2yS1j3oL2aZBVeeC6wbt7HemJMEgRmOBhFMKVVIfsHnEaoiBktngbJp8wslzgVuFkh7LoLxgCGD38CrTw4FJtgqPWm8celibMjnkPfD4L08IbaouxBoLG3SRQLMQeRovAETlqN4nFz0iwtJ4Q4O8vTEJxxMOZNv1fQKFKHDjP8WiW3odhdjBDQ4WdNG5INorUbuVcWAMma1MC80DSvi7WpCQUPvcpVyhAV+3rKk1D4pMgjnaO7L6wgj1b+2B0/OrJeo7lNfaNjAihKEeATvAnnV6ZEiftIyoINNcnU+ByWt41O+c5q6XIoRCpzi6VjaP27Y31uwEvWvWKRDPWkGpBNMIR1ZHiITA3/FrHLMN8etjY8zj0MdPLx/f6ayv3G5br3TO8extPGBWlMAZP/g9UU1gTWFv99KoOoccVOaJplmE/kksiEZykNRmQ89bhsQ7pvuaSku4OwjCDH78fMKyuyk7/VOkkMsSdrTW/RI1B2IXLz2ujtpOb0E4ojs9OdVSrs9mdJ7t53spmSv3IwOae7yppQsmKmZVFJVRMpXdD7UBVLbozMsgB+i0Hmqm9eDdw6C9k=
    - secure: EKEgKED+0E2p1/1UJAMwQIKTZWEUoe5aYFoNTV8Ew0tSdYCmUcTeXD5pPTZayG9RP6Jcnt4C6iZG5u9rCKIYSK33kiNs7K8dmHdp/0wmR2GLl8N0ohihuKQZLwCkgYLN2Og3fqWJeNnEtiFoMtRFifmzBUK1Vw7ILMoBrkmxVw5xXNfH/RI1wQZhGUVVeIfuTYDI7TBwfB8b50diDNBEhWX16TRpDShwsVxYFS5j3ED48srqQUySw+5HtIu5F9yJmioyBiNEfIFhoGXRC01QlfK+6+gNM9roC8915anarTOKZoAopTF9Srhi31AhyS5DPJb5wFJx6dutTolBMaqFEOXcZvlYCTs5Dl+5glZHU+NgY3B8APm6+O6V7F2JzQcr9wObVWG+AYno0b2qCVZ9WxdrIbImv4vsxHWrlhr+/6OmGhQlFdE8FjepPnE7numN4XGqymrVla6TmpcJY5MuAj1c3vfDGjpYIa1dDC9qPPO4C50a/VzieEP38K80OfGiIeEOnzIGIRrK4br3T3xHM/vp6IE5fNR/tSv0JTWW6Wiv9aPWCTai+V8Wk//JRmmat7cqpHKBDkf4CrEJ1BAD3c+PdM/DfU2vyYA+JhBaXkxK6fJGb3hVR0MN7Ov7xwiNkn12fvGIFVSOSWqbNtgszuBjgj76gUrD0PgTDGy5Sxs=
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
    - './node_modules'
install:
  - npm install
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
    > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - './cc-test-reporter before-build'
script:
  - ng test --no-watch --no-progress --codeCoverage --browsers=ChromeHeadlessCI
after_script:
  - './cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t lcov'
